// Generated by CoffeeScript 1.10.0
var Client;

Client = (function() {
  function Client() {}

  require("./definitions/tlds");

  Client.prototype.lookup = function(domain, callback, server) {
    console.log('Matched server:', server);
    console.log('domain', domain);
    if (!server) {
      return callback({
        validation: false,
        message: 'Top Level Domain not supported.'
      });
    } else {
      server = server[1];
      return server.lookup(domain, function(response) {
        return callback(response);
      });
    }
  };

  return Client;

})();

exports.client = Client;
