// Generated by CoffeeScript 1.10.0
var Base, Verisign,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Base = require("./base").base;

Verisign = (function(superClass) {
  extend(Verisign, superClass);

  function Verisign() {
    return Verisign.__super__.constructor.apply(this, arguments);
  }

  return Verisign;

})(Base);

exports.verisign = Verisign;
